/** CC0 / public-domain poster bank for agentic room auto-place. See docs/agentic-poster-bank.md */

export interface AgenticPosterBankEntry {
  kind: string;
  label: string;
  description: string;
  tags: string[];
  themes: string[];
  license: string;
  sourceUrl: string;
  /** Wikimedia Special:FilePath download (width capped). */
  imageFile: string;
  widthIn: number;
  heightIn: number;
  depthIn: number;
  modelPath: string;
  thumbnailPath: string;
}

export const AGENTIC_POSTER_BANK: readonly AgenticPosterBankEntry[] = [
  {
    kind: 'poster-gothic-cathedral',
    label: 'Gothic cathedral architecture wall poster',
    description: 'Medieval gothic cathedral cityscape for dark dorm rooms',
    tags: ['gothic', 'dark', 'medieval', 'architecture', 'cathedral'],
    themes: ['gothic', 'moody', 'dark'],
    license: 'Public domain (PD-Art)',
    sourceUrl: 'https://commons.wikimedia.org/wiki/File:Dommersen_Gothic_cathedral_in_a_medieval_city.jpg',
    imageFile: 'Dommersen_Gothic_cathedral_in_a_medieval_city.jpg',
    widthIn: 24,
    heightIn: 36,
    depthIn: 0.5,
    modelPath: 'checklist-refs/glb/posters/poster-gothic-cathedral.glb',
    thumbnailPath: 'checklist-refs/images/posters/poster-gothic-cathedral.jpg',
  },
  {
    kind: 'poster-coastal-beach',
    label: 'Coastal beach shoreline wall poster',
    description: 'Sandy ocean shoreline for coastal and beach-themed rooms',
    tags: ['coastal', 'beach', 'ocean', 'shore', 'sand', 'waves'],
    themes: ['coastal', 'beach', 'nautical'],
    license: 'CC0 1.0',
    sourceUrl: 'https://commons.wikimedia.org/wiki/File:Sandy_shoreline_(Unsplash).jpg',
    imageFile: 'Sandy_shoreline_(Unsplash).jpg',
    widthIn: 24,
    heightIn: 36,
    depthIn: 0.5,
    modelPath: 'checklist-refs/glb/posters/poster-coastal-beach.glb',
    thumbnailPath: 'checklist-refs/images/posters/poster-coastal-beach.jpg',
  },
  {
    kind: 'poster-minimalist-lines',
    label: 'Minimalist geometric line art wall poster',
    description: 'Simple black and white geometric lines for studio minimal rooms',
    tags: ['minimalist', 'geometric', 'line', 'abstract', 'modern'],
    themes: ['minimalist', 'studio', 'modern'],
    license: 'Public domain (PD-Art)',
    sourceUrl: 'https://commons.wikimedia.org/wiki/File:Composition-with-red-yellow-and-blue.jpg',
    imageFile: 'Composition-with-red-yellow-and-blue.jpg',
    widthIn: 24,
    heightIn: 36,
    depthIn: 0.5,
    modelPath: 'checklist-refs/glb/posters/poster-minimalist-lines.glb',
    thumbnailPath: 'checklist-refs/images/posters/poster-minimalist-lines.jpg',
  },
  {
    kind: 'poster-botanical-flowers',
    label: 'Botanical flower illustration wall poster',
    description: 'Vintage botanical flower print for nature and sage rooms',
    tags: ['botanical', 'flowers', 'floral', 'nature', 'garden', 'plants'],
    themes: ['botanical', 'sage', 'nature', 'floral'],
    license: 'Public domain (PD-Art)',
    sourceUrl: 'https://commons.wikimedia.org/wiki/File:Tulip_redoute.JPG',
    imageFile: 'Tulip_redoute.JPG',
    widthIn: 24,
    heightIn: 36,
    depthIn: 0.5,
    modelPath: 'checklist-refs/glb/posters/poster-botanical-flowers.glb',
    thumbnailPath: 'checklist-refs/images/posters/poster-botanical-flowers.jpg',
  },
  {
    kind: 'poster-space-nebula',
    label: 'Deep space nebula astronomy wall poster',
    description: 'Hubble crab nebula for space and sci-fi themed rooms',
    tags: ['space', 'nebula', 'astronomy', 'stars', 'cosmos', 'galaxy'],
    themes: ['space', 'sci-fi', 'cosmic'],
    license: 'Public domain (NASA/STScI)',
    sourceUrl: 'https://commons.wikimedia.org/wiki/File:Crab_Nebula.jpg',
    imageFile: 'Crab_Nebula.jpg',
    widthIn: 24,
    heightIn: 36,
    depthIn: 0.5,
    modelPath: 'checklist-refs/glb/posters/poster-space-nebula.glb',
    thumbnailPath: 'checklist-refs/images/posters/poster-space-nebula.jpg',
  },
  {
    kind: 'poster-vintage-travel',
    label: 'Vintage travel city wall poster',
    description: 'Classic travel poster style cityscape for eclectic dorm decor',
    tags: ['vintage', 'travel', 'city', 'retro', 'tourism'],
    themes: ['vintage', 'travel', 'retro'],
    license: 'Public domain (PD-Art)',
    sourceUrl: 'https://commons.wikimedia.org/wiki/File:Cook%27s_Nile_and_Palestine_Tours_poster_-_circa_1902.jpg',
    imageFile: "Cook's_Nile_and_Palestine_Tours_poster_-_circa_1902.jpg",
    widthIn: 24,
    heightIn: 36,
    depthIn: 0.5,
    modelPath: 'checklist-refs/glb/posters/poster-vintage-travel.glb',
    thumbnailPath: 'checklist-refs/images/posters/poster-vintage-travel.jpg',
  },
  {
    kind: 'poster-japanese-woodblock',
    label: 'Japanese woodblock wave landscape wall poster',
    description: 'Hokusai great wave print for anime-adjacent and zen rooms',
    tags: ['japanese', 'woodblock', 'wave', 'landscape', 'ukiyo-e', 'mountain'],
    themes: ['anime', 'japanese', 'zen', 'coastal'],
    license: 'CC0 1.0 (Art Institute of Chicago)',
    sourceUrl: 'https://commons.wikimedia.org/wiki/File:The_Great_Wave_off_Kanagawa.png',
    imageFile: 'The_Great_Wave_off_Kanagawa.png',
    widthIn: 24,
    heightIn: 36,
    depthIn: 0.5,
    modelPath: 'checklist-refs/glb/posters/poster-japanese-woodblock.glb',
    thumbnailPath: 'checklist-refs/images/posters/poster-japanese-woodblock.jpg',
  },
  {
    kind: 'poster-dorm-motivation',
    label: 'Motivational typography wall poster',
    description: 'Bold typographic quote art for dorm inspiration walls',
    tags: ['motivational', 'typography', 'quote', 'dorm', 'inspiration', 'text'],
    themes: ['dorm', 'motivation', 'study'],
    license: 'CC0 1.0',
    sourceUrl: 'https://commons.wikimedia.org/wiki/File:Keep-calm-and-carry-on-scan.jpg',
    imageFile: 'Keep-calm-and-carry-on-scan.jpg',
    widthIn: 18,
    heightIn: 24,
    depthIn: 0.5,
    modelPath: 'checklist-refs/glb/posters/poster-dorm-motivation.glb',
    thumbnailPath: 'checklist-refs/images/posters/poster-dorm-motivation.jpg',
  },
  {
    kind: 'poster-sage-forest',
    label: 'Sage green forest nature wall poster',
    description: 'Green forest landscape for sage and nature vibe rooms',
    tags: ['sage', 'forest', 'green', 'nature', 'trees', 'woodland'],
    themes: ['sage', 'nature', 'green'],
    license: 'CC0 1.0',
    sourceUrl: 'https://commons.wikimedia.org/wiki/File:Forest_path_surrounded_by_green_trees.jpg',
    imageFile: 'Forest_path_surrounded_by_green_trees.jpg',
    widthIn: 24,
    heightIn: 36,
    depthIn: 0.5,
    modelPath: 'checklist-refs/glb/posters/poster-sage-forest.glb',
    thumbnailPath: 'checklist-refs/images/posters/poster-sage-forest.jpg',
  },
  {
    kind: 'poster-moody-charcoal',
    label: 'Moody charcoal architecture wall poster',
    description: 'Dark gothic church interior for moody and dark rooms',
    tags: ['moody', 'dark', 'charcoal', 'gothic', 'church', 'interior'],
    themes: ['moody', 'gothic', 'dark'],
    license: 'Public domain (LACMA)',
    sourceUrl: 'https://commons.wikimedia.org/wiki/File:Interior_of_a_Gothic_Cathedral_LACMA_49.17.5.jpg',
    imageFile: 'Interior_of_a_Gothic_Cathedral_LACMA_49.17.5.jpg',
    widthIn: 24,
    heightIn: 36,
    depthIn: 0.5,
    modelPath: 'checklist-refs/glb/posters/poster-moody-charcoal.glb',
    thumbnailPath: 'checklist-refs/images/posters/poster-moody-charcoal.jpg',
  },
  {
    kind: 'poster-studio-geometric',
    label: 'Studio geometric abstract wall poster',
    description: 'Color-block abstract art for modern studio workspaces',
    tags: ['studio', 'geometric', 'abstract', 'modern', 'color', 'blocks'],
    themes: ['studio', 'modern', 'minimalist'],
    license: 'Public domain (PD-Art)',
    sourceUrl: 'https://commons.wikimedia.org/wiki/File:Piet_Mondriaan,_1930_-_Mondrian_Composition_II_in_Red,_Blue,_and_Yellow.jpg',
    imageFile: 'Piet_Mondriaan,_1930_-_Mondrian_Composition_II_in_Red,_Blue,_and_Yellow.jpg',
    widthIn: 24,
    heightIn: 36,
    depthIn: 0.5,
    modelPath: 'checklist-refs/glb/posters/poster-studio-geometric.glb',
    thumbnailPath: 'checklist-refs/images/posters/poster-studio-geometric.jpg',
  },
  {
    kind: 'poster-warm-sunset',
    label: 'Warm sunset beach landscape wall poster',
    description: 'Golden hour coastal sunset for warm and cozy rooms',
    tags: ['warm', 'sunset', 'beach', 'golden', 'coastal', 'sky'],
    themes: ['warm', 'coastal', 'cozy', 'sunset'],
    license: 'CC0 1.0',
    sourceUrl: 'https://commons.wikimedia.org/wiki/File:Marshall_Beach_Sunset_(6753666737).jpg',
    imageFile: 'Marshall_Beach_Sunset_(6753666737).jpg',
    widthIn: 24,
    heightIn: 36,
    depthIn: 0.5,
    modelPath: 'checklist-refs/glb/posters/poster-warm-sunset.glb',
    thumbnailPath: 'checklist-refs/images/posters/poster-warm-sunset.jpg',
  },
  {
    kind: 'poster-neutral-abstract',
    label: 'Neutral abstract color wall poster',
    description: 'Soft neutral abstract wash for balanced dorm rooms',
    tags: ['neutral', 'abstract', 'soft', 'beige', 'minimal', 'calm'],
    themes: ['neutral', 'calm', 'minimalist'],
    license: 'CC0 1.0',
    sourceUrl: 'https://commons.wikimedia.org/wiki/File:Palisades_Beach.jpg',
    imageFile: 'Palisades_Beach.jpg',
    widthIn: 24,
    heightIn: 36,
    depthIn: 0.5,
    modelPath: 'checklist-refs/glb/posters/poster-neutral-abstract.glb',
    thumbnailPath: 'checklist-refs/images/posters/poster-neutral-abstract.jpg',
  },
  {
    kind: 'poster-pixel-blocks',
    label: 'Green pixel block landscape wall poster',
    description: 'Block-style green landscape for voxel and sandbox gaming rooms',
    tags: ['pixel', 'block', 'voxel', 'gaming', 'landscape', '8-bit', 'grass'],
    themes: ['gaming', 'pixel', 'block', 'minecraft', 'voxel'],
    license: 'CC0 1.0 (Toova procedural)',
    sourceUrl: 'https://toova.app/posters/poster-pixel-blocks',
    imageFile: 'procedural:pixel-blocks',
    widthIn: 24,
    heightIn: 36,
    depthIn: 0.5,
    modelPath: 'checklist-refs/glb/posters/poster-pixel-blocks.glb',
    thumbnailPath: 'checklist-refs/images/posters/poster-pixel-blocks.png',
  },
  {
    kind: 'poster-ascii-gaming',
    label: 'Retro ASCII gaming wall poster',
    description: 'Retro terminal ASCII aesthetic for gaming dorm rooms',
    tags: ['ascii', 'retro', 'gaming', 'terminal', '8-bit', 'pixel'],
    themes: ['gaming', 'pixel', 'retro', 'ascii'],
    license: 'CC0 1.0 (Toova procedural)',
    sourceUrl: 'https://toova.app/posters/poster-ascii-gaming',
    imageFile: 'procedural:ascii-gaming',
    widthIn: 24,
    heightIn: 36,
    depthIn: 0.5,
    modelPath: 'checklist-refs/glb/posters/poster-ascii-gaming.glb',
    thumbnailPath: 'checklist-refs/images/posters/poster-ascii-gaming.png',
  },
  {
    kind: 'poster-retro-arcade',
    label: 'Retro arcade gaming wall poster',
    description: 'Neon arcade cabinet pixel art for retro gaming rooms',
    tags: ['arcade', 'retro', 'gaming', 'neon', 'cabinet', 'pixel'],
    themes: ['gaming', 'pixel', 'retro', 'arcade'],
    license: 'CC0 1.0 (Toova procedural)',
    sourceUrl: 'https://toova.app/posters/poster-retro-arcade',
    imageFile: 'procedural:retro-arcade',
    widthIn: 24,
    heightIn: 36,
    depthIn: 0.5,
    modelPath: 'checklist-refs/glb/posters/poster-retro-arcade.glb',
    thumbnailPath: 'checklist-refs/images/posters/poster-retro-arcade.png',
  },
  {
    kind: 'poster-pixel-landscape',
    label: 'Retro pixel gaming wall poster',
    description: 'Retro 8-bit computer aesthetic for gaming dorm rooms',
    tags: ['pixel', 'block', 'retro', 'gaming', 'landscape', '8-bit'],
    themes: ['gaming', 'pixel', 'retro', 'minecraft'],
    license: 'Public domain (PD-Art)',
    sourceUrl: 'https://commons.wikimedia.org/wiki/File:Commodore-64-Computer-FL.jpg',
    imageFile: 'Commodore-64-Computer-FL.jpg',
    widthIn: 24,
    heightIn: 36,
    depthIn: 0.5,
    modelPath: 'checklist-refs/glb/posters/poster-pixel-landscape.glb',
    thumbnailPath: 'checklist-refs/images/posters/poster-pixel-landscape.jpg',
  },
  {
    kind: 'poster-mountain-landscape',
    label: 'Mountain landscape wall poster',
    description: 'Alpine mountain vista for nature and adventure themes',
    tags: ['mountain', 'landscape', 'alpine', 'nature', 'peaks', 'outdoors'],
    themes: ['nature', 'adventure', 'sage', 'outdoors'],
    license: 'CC0 1.0',
    sourceUrl: 'https://commons.wikimedia.org/wiki/File:Wonder_Lake,_Denali.jpg',
    imageFile: 'Wonder_Lake,_Denali.jpg',
    widthIn: 24,
    heightIn: 36,
    depthIn: 0.5,
    modelPath: 'checklist-refs/glb/posters/poster-mountain-landscape.glb',
    thumbnailPath: 'checklist-refs/images/posters/poster-mountain-landscape.jpg',
  },
];

export function posterBankByKind(kind: string): AgenticPosterBankEntry | undefined {
  return AGENTIC_POSTER_BANK.find((p) => p.kind === kind);
}
