-- CC0 / public-domain agentic poster bank (built via scripts/build-poster-bank.mjs)

INSERT INTO public.furniture_catalog (
  kind, label, description, width_in, height_in, depth_in, clearance_in,
  is_builtin, model_url, thumbnail_path, tags, categories, visibility
) VALUES
(
  'poster-gothic-cathedral',
  'Gothic cathedral architecture wall poster',
  'Gothic cathedral architecture wall poster — CC0/public-domain Toova poster bank',
  26.82, 36, 0.5, null,
  true,
  'checklist-refs/glb/posters/poster-gothic-cathedral.glb',
  'checklist-refs/images/posters/poster-gothic-cathedral.jpg',
  '{"gothic","dark","medieval","architecture","cathedral","poster"}'::text[],
  ARRAY['decor_art'],
  'public'
),
(
  'poster-coastal-beach',
  'Coastal beach shoreline wall poster',
  'Coastal beach shoreline wall poster — CC0/public-domain Toova poster bank',
  55.88, 36, 0.5, null,
  true,
  'checklist-refs/glb/posters/poster-coastal-beach.glb',
  'checklist-refs/images/posters/poster-coastal-beach.jpg',
  '{"coastal","beach","ocean","shore","sand","waves","poster"}'::text[],
  ARRAY['decor_art'],
  'public'
),
(
  'poster-minimalist-lines',
  'Minimalist geometric line art wall poster',
  'Minimalist geometric line art wall poster — CC0/public-domain Toova poster bank',
  34.14, 36, 0.5, null,
  true,
  'checklist-refs/glb/posters/poster-minimalist-lines.glb',
  'checklist-refs/images/posters/poster-minimalist-lines.jpg',
  '{"minimalist","geometric","line","abstract","modern","poster"}'::text[],
  ARRAY['decor_art'],
  'public'
),
(
  'poster-botanical-flowers',
  'Botanical flower illustration wall poster',
  'Botanical flower illustration wall poster — CC0/public-domain Toova poster bank',
  21.02, 36, 0.5, null,
  true,
  'checklist-refs/glb/posters/poster-botanical-flowers.glb',
  'checklist-refs/images/posters/poster-botanical-flowers.jpg',
  '{"botanical","flowers","floral","nature","garden","plants","poster"}'::text[],
  ARRAY['decor_art'],
  'public'
),
(
  'poster-space-nebula',
  'Deep space nebula astronomy wall poster',
  'Deep space nebula astronomy wall poster — CC0/public-domain Toova poster bank',
  36, 36, 0.5, null,
  true,
  'checklist-refs/glb/posters/poster-space-nebula.glb',
  'checklist-refs/images/posters/poster-space-nebula.jpg',
  '{"space","nebula","astronomy","stars","cosmos","galaxy","poster"}'::text[],
  ARRAY['decor_art'],
  'public'
),
(
  'poster-vintage-travel',
  'Vintage travel city wall poster',
  'Vintage travel city wall poster — CC0/public-domain Toova poster bank',
  22.39, 36, 0.5, null,
  true,
  'checklist-refs/glb/posters/poster-vintage-travel.glb',
  'checklist-refs/images/posters/poster-vintage-travel.jpg',
  '{"vintage","travel","city","retro","tourism","poster"}'::text[],
  ARRAY['decor_art'],
  'public'
),
(
  'poster-japanese-woodblock',
  'Japanese woodblock wave landscape wall poster',
  'Japanese woodblock wave landscape wall poster — CC0/public-domain Toova poster bank',
  68.82, 36, 0.5, null,
  true,
  'checklist-refs/glb/posters/poster-japanese-woodblock.glb',
  'checklist-refs/images/posters/poster-japanese-woodblock.png',
  '{"japanese","woodblock","wave","landscape","ukiyo-e","mountain","poster"}'::text[],
  ARRAY['decor_art'],
  'public'
),
(
  'poster-dorm-motivation',
  'Motivational typography wall poster',
  'Motivational typography wall poster — CC0/public-domain Toova poster bank',
  16.05, 24, 0.5, null,
  true,
  'checklist-refs/glb/posters/poster-dorm-motivation.glb',
  'checklist-refs/images/posters/poster-dorm-motivation.jpg',
  '{"motivational","typography","quote","dorm","inspiration","text","poster"}'::text[],
  ARRAY['decor_art'],
  'public'
),
(
  'poster-sage-forest',
  'Sage green forest nature wall poster',
  'Sage green forest nature wall poster — CC0/public-domain Toova poster bank',
  54, 36, 0.5, null,
  true,
  'checklist-refs/glb/posters/poster-sage-forest.glb',
  'checklist-refs/images/posters/poster-sage-forest.jpg',
  '{"sage","forest","green","nature","trees","woodland","poster"}'::text[],
  ARRAY['decor_art'],
  'public'
),
(
  'poster-moody-charcoal',
  'Moody charcoal architecture wall poster',
  'Moody charcoal architecture wall poster — CC0/public-domain Toova poster bank',
  46.51, 36, 0.5, null,
  true,
  'checklist-refs/glb/posters/poster-moody-charcoal.glb',
  'checklist-refs/images/posters/poster-moody-charcoal.jpg',
  '{"moody","dark","charcoal","gothic","church","interior","poster"}'::text[],
  ARRAY['decor_art'],
  'public'
),
(
  'poster-studio-geometric',
  'Studio geometric abstract wall poster',
  'Studio geometric abstract wall poster — CC0/public-domain Toova poster bank',
  35.5, 36, 0.5, null,
  true,
  'checklist-refs/glb/posters/poster-studio-geometric.glb',
  'checklist-refs/images/posters/poster-studio-geometric.jpg',
  '{"studio","geometric","abstract","modern","color","blocks","poster"}'::text[],
  ARRAY['decor_art'],
  'public'
),
(
  'poster-warm-sunset',
  'Warm sunset beach landscape wall poster',
  'Warm sunset beach landscape wall poster — CC0/public-domain Toova poster bank',
  57.74, 36, 0.5, null,
  true,
  'checklist-refs/glb/posters/poster-warm-sunset.glb',
  'checklist-refs/images/posters/poster-warm-sunset.jpg',
  '{"warm","sunset","beach","golden","coastal","sky","poster"}'::text[],
  ARRAY['decor_art'],
  'public'
),
(
  'poster-neutral-abstract',
  'Neutral abstract color wall poster',
  'Neutral abstract color wall poster — CC0/public-domain Toova poster bank',
  54, 36, 0.5, null,
  true,
  'checklist-refs/glb/posters/poster-neutral-abstract.glb',
  'checklist-refs/images/posters/poster-neutral-abstract.jpg',
  '{"neutral","abstract","soft","beige","minimal","calm","poster"}'::text[],
  ARRAY['decor_art'],
  'public'
),
(
  'poster-pixel-blocks',
  'Green pixel block landscape wall poster',
  'Green pixel block landscape wall poster — CC0/public-domain Toova poster bank',
  24, 36, 0.5, null,
  true,
  'checklist-refs/glb/posters/poster-pixel-blocks.glb',
  'checklist-refs/images/posters/poster-pixel-blocks.png',
  '{"pixel","block","voxel","gaming","landscape","8-bit","grass","poster"}'::text[],
  ARRAY['decor_art'],
  'public'
),
(
  'poster-ascii-gaming',
  'Retro ASCII gaming wall poster',
  'Retro ASCII gaming wall poster — CC0/public-domain Toova poster bank',
  24, 36, 0.5, null,
  true,
  'checklist-refs/glb/posters/poster-ascii-gaming.glb',
  'checklist-refs/images/posters/poster-ascii-gaming.png',
  '{"ascii","retro","gaming","terminal","8-bit","pixel","poster"}'::text[],
  ARRAY['decor_art'],
  'public'
),
(
  'poster-retro-arcade',
  'Retro arcade gaming wall poster',
  'Retro arcade gaming wall poster — CC0/public-domain Toova poster bank',
  24, 36, 0.5, null,
  true,
  'checklist-refs/glb/posters/poster-retro-arcade.glb',
  'checklist-refs/images/posters/poster-retro-arcade.png',
  '{"arcade","retro","gaming","neon","cabinet","pixel","poster"}'::text[],
  ARRAY['decor_art'],
  'public'
),
(
  'poster-pixel-landscape',
  'Retro pixel gaming wall poster',
  'Retro pixel gaming wall poster — CC0/public-domain Toova poster bank',
  63.71, 36, 0.5, null,
  true,
  'checklist-refs/glb/posters/poster-pixel-landscape.glb',
  'checklist-refs/images/posters/poster-pixel-landscape.jpg',
  '{"pixel","block","retro","gaming","landscape","8-bit","poster"}'::text[],
  ARRAY['decor_art'],
  'public'
),
(
  'poster-mountain-landscape',
  'Mountain landscape wall poster',
  'Mountain landscape wall poster — CC0/public-domain Toova poster bank',
  49.37, 36, 0.5, null,
  true,
  'checklist-refs/glb/posters/poster-mountain-landscape.glb',
  'checklist-refs/images/posters/poster-mountain-landscape.jpg',
  '{"mountain","landscape","alpine","nature","peaks","outdoors","poster"}'::text[],
  ARRAY['decor_art'],
  'public'
),
(
  'poster-starry-night',
  'Starry night impressionist wall poster',
  'Starry night impressionist wall poster — CC0/public-domain Toova poster bank',
  37.1, 36, 0.5, null,
  true,
  'checklist-refs/glb/posters/poster-starry-night.glb',
  'checklist-refs/images/posters/poster-starry-night.jpg',
  '{"impressionist","starry","night","blue","swirl","classic","poster"}'::text[],
  ARRAY['decor_art'],
  'public'
),
(
  'poster-water-lilies',
  'Water lilies impressionist wall poster',
  'Water lilies impressionist wall poster — CC0/public-domain Toova poster bank',
  37.46, 36, 0.5, null,
  true,
  'checklist-refs/glb/posters/poster-water-lilies.glb',
  'checklist-refs/images/posters/poster-water-lilies.jpg',
  '{"impressionist","water","lilies","pond","green","soft","poster"}'::text[],
  ARRAY['decor_art'],
  'public'
),
(
  'poster-pillars-creation',
  'Deep space pillars astronomy wall poster',
  'Deep space pillars astronomy wall poster — CC0/public-domain Toova poster bank',
  34.53, 36, 0.5, null,
  true,
  'checklist-refs/glb/posters/poster-pillars-creation.glb',
  'checklist-refs/images/posters/poster-pillars-creation.jpg',
  '{"space","nebula","pillars","hubble","cosmos","stars","poster"}'::text[],
  ARRAY['decor_art'],
  'public'
),
(
  'poster-earthrise',
  'Earthrise space photography wall poster',
  'Earthrise space photography wall poster — CC0/public-domain Toova poster bank',
  45, 36, 0.5, null,
  true,
  'checklist-refs/glb/posters/poster-earthrise.glb',
  'checklist-refs/images/posters/poster-earthrise.jpg',
  '{"space","earth","planet","nasa","orbit","cosmos","poster"}'::text[],
  ARRAY['decor_art'],
  'public'
),
(
  'poster-blue-marble',
  'Blue marble earth from space wall poster',
  'Blue marble earth from space wall poster — CC0/public-domain Toova poster bank',
  36, 36, 0.5, null,
  true,
  'checklist-refs/glb/posters/poster-blue-marble.glb',
  'checklist-refs/images/posters/poster-blue-marble.jpg',
  '{"space","earth","planet","nasa","blue","globe","poster"}'::text[],
  ARRAY['decor_art'],
  'public'
),
(
  'poster-full-moon',
  'Full moon night sky wall poster',
  'Full moon night sky wall poster — CC0/public-domain Toova poster bank',
  35.67, 36, 0.5, null,
  true,
  'checklist-refs/glb/posters/poster-full-moon.glb',
  'checklist-refs/images/posters/poster-full-moon.jpg',
  '{"moon","night","lunar","sky","astronomy","silver","poster"}'::text[],
  ARRAY['decor_art'],
  'public'
),
(
  'poster-butterfly-botanical',
  'Monarch butterfly botanical wall poster',
  'Monarch butterfly botanical wall poster — CC0/public-domain Toova poster bank',
  48, 36, 0.5, null,
  true,
  'checklist-refs/glb/posters/poster-butterfly-botanical.glb',
  'checklist-refs/images/posters/poster-butterfly-botanical.jpg',
  '{"butterfly","botanical","insect","nature","orange","garden","poster"}'::text[],
  ARRAY['decor_art'],
  'public'
),
(
  'poster-hot-air-balloons',
  'Hot air balloon sky wall poster',
  'Hot air balloon sky wall poster — CC0/public-domain Toova poster bank',
  52.36, 36, 0.5, null,
  true,
  'checklist-refs/glb/posters/poster-hot-air-balloons.glb',
  'checklist-refs/images/posters/poster-hot-air-balloons.jpg',
  '{"balloon","sky","travel","adventure","colorful","air","poster"}'::text[],
  ARRAY['decor_art'],
  'public'
),
(
  'poster-niagara-falls',
  'Niagara falls waterfall wall poster',
  'Niagara falls waterfall wall poster — CC0/public-domain Toova poster bank',
  54.25, 36, 0.5, null,
  true,
  'checklist-refs/glb/posters/poster-niagara-falls.glb',
  'checklist-refs/images/posters/poster-niagara-falls.jpg',
  '{"waterfall","nature","mist","river","landscape","outdoors","poster"}'::text[],
  ARRAY['decor_art'],
  'public'
),
(
  'poster-cherry-blossoms',
  'Cherry blossom spring wall poster',
  'Cherry blossom spring wall poster — CC0/public-domain Toova poster bank',
  54, 36, 0.5, null,
  true,
  'checklist-refs/glb/posters/poster-cherry-blossoms.glb',
  'checklist-refs/images/posters/poster-cherry-blossoms.jpg',
  '{"cherry","blossom","spring","pink","floral","japanese","poster"}'::text[],
  ARRAY['decor_art'],
  'public'
),
(
  'poster-vintage-bicycle',
  'Vintage bicycle street wall poster',
  'Vintage bicycle street wall poster — CC0/public-domain Toova poster bank',
  54, 36, 0.5, null,
  true,
  'checklist-refs/glb/posters/poster-vintage-bicycle.glb',
  'checklist-refs/images/posters/poster-vintage-bicycle.jpg',
  '{"bicycle","vintage","street","urban","retro","travel","poster"}'::text[],
  ARRAY['decor_art'],
  'public'
),
(
  'poster-forest-waterfall',
  'Forest waterfall nature wall poster',
  'Forest waterfall nature wall poster — CC0/public-domain Toova poster bank',
  54, 36, 0.5, null,
  true,
  'checklist-refs/glb/posters/poster-forest-waterfall.glb',
  'checklist-refs/images/posters/poster-forest-waterfall.jpg',
  '{"waterfall","forest","green","nature","stream","outdoors","poster"}'::text[],
  ARRAY['decor_art'],
  'public'
),
(
  'poster-lavender-field',
  'Lavender field purple wall poster',
  'Lavender field purple wall poster — CC0/public-domain Toova poster bank',
  54, 36, 0.5, null,
  true,
  'checklist-refs/glb/posters/poster-lavender-field.glb',
  'checklist-refs/images/posters/poster-lavender-field.jpg',
  '{"lavender","purple","field","floral","summer","calm","poster"}'::text[],
  ARRAY['decor_art'],
  'public'
),
(
  'poster-surf-wave',
  'Surfing ocean wave wall poster',
  'Surfing ocean wave wall poster — CC0/public-domain Toova poster bank',
  48, 36, 0.5, null,
  true,
  'checklist-refs/glb/posters/poster-surf-wave.glb',
  'checklist-refs/images/posters/poster-surf-wave.jpg',
  '{"surf","wave","ocean","beach","blue","sport","poster"}'::text[],
  ARRAY['decor_art'],
  'public'
),
(
  'poster-scream-expressionist',
  'Expressionist portrait wall poster',
  'Expressionist portrait wall poster — CC0/public-domain Toova poster bank',
  28.47, 36, 0.5, null,
  true,
  'checklist-refs/glb/posters/poster-scream-expressionist.glb',
  'checklist-refs/images/posters/poster-scream-expressionist.jpg',
  '{"expressionist","portrait","dramatic","art","classic","moody","poster"}'::text[],
  ARRAY['decor_art'],
  'public'
),
(
  'poster-aurora-gradient',
  'Aurora borealis gradient wall poster',
  'Aurora borealis gradient wall poster — CC0/public-domain Toova poster bank',
  24, 36, 0.5, null,
  true,
  'checklist-refs/glb/posters/poster-aurora-gradient.glb',
  'checklist-refs/images/posters/poster-aurora-gradient.png',
  '{"aurora","northern","lights","green","purple","sky","poster"}'::text[],
  ARRAY['decor_art'],
  'public'
),
(
  'poster-desert-sunset',
  'Desert sunset landscape wall poster',
  'Desert sunset landscape wall poster — CC0/public-domain Toova poster bank',
  24, 36, 0.5, null,
  true,
  'checklist-refs/glb/posters/poster-desert-sunset.glb',
  'checklist-refs/images/posters/poster-desert-sunset.png',
  '{"desert","sunset","warm","sand","dunes","golden","poster"}'::text[],
  ARRAY['decor_art'],
  'public'
),
(
  'poster-ocean-deep',
  'Deep ocean blue wall poster',
  'Deep ocean blue wall poster — CC0/public-domain Toova poster bank',
  24, 36, 0.5, null,
  true,
  'checklist-refs/glb/posters/poster-ocean-deep.glb',
  'checklist-refs/images/posters/poster-ocean-deep.png',
  '{"ocean","deep","blue","water","sea","calm","poster"}'::text[],
  ARRAY['decor_art'],
  'public'
),
(
  'poster-forest-mist',
  'Misty green forest wall poster',
  'Misty green forest wall poster — CC0/public-domain Toova poster bank',
  24, 36, 0.5, null,
  true,
  'checklist-refs/glb/posters/poster-forest-mist.glb',
  'checklist-refs/images/posters/poster-forest-mist.png',
  '{"forest","mist","green","woodland","nature","trees","poster"}'::text[],
  ARRAY['decor_art'],
  'public'
),
(
  'poster-cherry-blossom-pink',
  'Pink cherry blossom abstract wall poster',
  'Pink cherry blossom abstract wall poster — CC0/public-domain Toova poster bank',
  24, 36, 0.5, null,
  true,
  'checklist-refs/glb/posters/poster-cherry-blossom-pink.glb',
  'checklist-refs/images/posters/poster-cherry-blossom-pink.png',
  '{"cherry","blossom","pink","floral","soft","spring","poster"}'::text[],
  ARRAY['decor_art'],
  'public'
),
(
  'poster-synthwave',
  'Synthwave retro grid wall poster',
  'Synthwave retro grid wall poster — CC0/public-domain Toova poster bank',
  24, 36, 0.5, null,
  true,
  'checklist-refs/glb/posters/poster-synthwave.glb',
  'checklist-refs/images/posters/poster-synthwave.png',
  '{"synthwave","retro","neon","grid","80s","purple","poster"}'::text[],
  ARRAY['decor_art'],
  'public'
),
(
  'poster-neon-grid',
  'Neon city grid wall poster',
  'Neon city grid wall poster — CC0/public-domain Toova poster bank',
  24, 36, 0.5, null,
  true,
  'checklist-refs/glb/posters/poster-neon-grid.glb',
  'checklist-refs/images/posters/poster-neon-grid.png',
  '{"neon","grid","city","cyber","blue","pink","poster"}'::text[],
  ARRAY['decor_art'],
  'public'
),
(
  'poster-zen-stones',
  'Zen stacked stones wall poster',
  'Zen stacked stones wall poster — CC0/public-domain Toova poster bank',
  24, 36, 0.5, null,
  true,
  'checklist-refs/glb/posters/poster-zen-stones.glb',
  'checklist-refs/images/posters/poster-zen-stones.png',
  '{"zen","stones","calm","minimal","balance","meditation","poster"}'::text[],
  ARRAY['decor_art'],
  'public'
),
(
  'poster-starfield',
  'Night starfield sky wall poster',
  'Night starfield sky wall poster — CC0/public-domain Toova poster bank',
  24, 36, 0.5, null,
  true,
  'checklist-refs/glb/posters/poster-starfield.glb',
  'checklist-refs/images/posters/poster-starfield.png',
  '{"stars","night","sky","cosmos","dark","sparkle","poster"}'::text[],
  ARRAY['decor_art'],
  'public'
),
(
  'poster-terrazzo',
  'Terrazzo pattern wall poster',
  'Terrazzo pattern wall poster — CC0/public-domain Toova poster bank',
  24, 36, 0.5, null,
  true,
  'checklist-refs/glb/posters/poster-terrazzo.glb',
  'checklist-refs/images/posters/poster-terrazzo.png',
  '{"terrazzo","pattern","speckle","modern","neutral","texture","poster"}'::text[],
  ARRAY['decor_art'],
  'public'
),
(
  'poster-marble-swirl',
  'Marble swirl texture wall poster',
  'Marble swirl texture wall poster — CC0/public-domain Toova poster bank',
  24, 36, 0.5, null,
  true,
  'checklist-refs/glb/posters/poster-marble-swirl.glb',
  'checklist-refs/images/posters/poster-marble-swirl.png',
  '{"marble","swirl","texture","neutral","luxury","soft","poster"}'::text[],
  ARRAY['decor_art'],
  'public'
),
(
  'poster-geometric-grid',
  'Colorful geometric grid wall poster',
  'Colorful geometric grid wall poster — CC0/public-domain Toova poster bank',
  24, 36, 0.5, null,
  true,
  'checklist-refs/glb/posters/poster-geometric-grid.glb',
  'checklist-refs/images/posters/poster-geometric-grid.png',
  '{"geometric","grid","color","blocks","modern","abstract","poster"}'::text[],
  ARRAY['decor_art'],
  'public'
),
(
  'poster-lavender-mist',
  'Lavender mist gradient wall poster',
  'Lavender mist gradient wall poster — CC0/public-domain Toova poster bank',
  24, 36, 0.5, null,
  true,
  'checklist-refs/glb/posters/poster-lavender-mist.glb',
  'checklist-refs/images/posters/poster-lavender-mist.png',
  '{"lavender","purple","mist","soft","calm","pastel","poster"}'::text[],
  ARRAY['decor_art'],
  'public'
),
(
  'poster-autumn-leaves',
  'Autumn leaves warm wall poster',
  'Autumn leaves warm wall poster — CC0/public-domain Toova poster bank',
  24, 36, 0.5, null,
  true,
  'checklist-refs/glb/posters/poster-autumn-leaves.glb',
  'checklist-refs/images/posters/poster-autumn-leaves.png',
  '{"autumn","leaves","orange","fall","warm","seasonal","poster"}'::text[],
  ARRAY['decor_art'],
  'public'
),
(
  'poster-winter-frost',
  'Winter frost icy wall poster',
  'Winter frost icy wall poster — CC0/public-domain Toova poster bank',
  24, 36, 0.5, null,
  true,
  'checklist-refs/glb/posters/poster-winter-frost.glb',
  'checklist-refs/images/posters/poster-winter-frost.png',
  '{"winter","frost","ice","blue","cold","seasonal","poster"}'::text[],
  ARRAY['decor_art'],
  'public'
),
(
  'poster-tropical-sunset',
  'Tropical palm sunset wall poster',
  'Tropical palm sunset wall poster — CC0/public-domain Toova poster bank',
  24, 36, 0.5, null,
  true,
  'checklist-refs/glb/posters/poster-tropical-sunset.glb',
  'checklist-refs/images/posters/poster-tropical-sunset.png',
  '{"tropical","palm","sunset","warm","beach","paradise","poster"}'::text[],
  ARRAY['decor_art'],
  'public'
),
(
  'poster-coral-underwater',
  'Coral reef underwater wall poster',
  'Coral reef underwater wall poster — CC0/public-domain Toova poster bank',
  24, 36, 0.5, null,
  true,
  'checklist-refs/glb/posters/poster-coral-underwater.glb',
  'checklist-refs/images/posters/poster-coral-underwater.png',
  '{"coral","reef","underwater","ocean","colorful","sea","poster"}'::text[],
  ARRAY['decor_art'],
  'public'
),
(
  'poster-coffee-warm',
  'Warm coffee tones wall poster',
  'Warm coffee tones wall poster — CC0/public-domain Toova poster bank',
  24, 36, 0.5, null,
  true,
  'checklist-refs/glb/posters/poster-coffee-warm.glb',
  'checklist-refs/images/posters/poster-coffee-warm.png',
  '{"coffee","warm","brown","cozy","cafe","rich","poster"}'::text[],
  ARRAY['decor_art'],
  'public'
),
(
  'poster-blush-abstract',
  'Blush pink abstract wall poster',
  'Blush pink abstract wall poster — CC0/public-domain Toova poster bank',
  24, 36, 0.5, null,
  true,
  'checklist-refs/glb/posters/poster-blush-abstract.glb',
  'checklist-refs/images/posters/poster-blush-abstract.png',
  '{"blush","pink","abstract","soft","pastel","feminine","poster"}'::text[],
  ARRAY['decor_art'],
  'public'
),
(
  'poster-navy-stripes',
  'Navy nautical stripes wall poster',
  'Navy nautical stripes wall poster — CC0/public-domain Toova poster bank',
  24, 36, 0.5, null,
  true,
  'checklist-refs/glb/posters/poster-navy-stripes.glb',
  'checklist-refs/images/posters/poster-navy-stripes.png',
  '{"navy","stripes","nautical","blue","classic","preppy","poster"}'::text[],
  ARRAY['decor_art'],
  'public'
),
(
  'poster-chess-board',
  'Chess board pattern wall poster',
  'Chess board pattern wall poster — CC0/public-domain Toova poster bank',
  24, 36, 0.5, null,
  true,
  'checklist-refs/glb/posters/poster-chess-board.glb',
  'checklist-refs/images/posters/poster-chess-board.png',
  '{"chess","board","pattern","game","black","white","poster"}'::text[],
  ARRAY['decor_art'],
  'public'
),
(
  'poster-vinyl-record',
  'Vintage vinyl record wall poster',
  'Vintage vinyl record wall poster — CC0/public-domain Toova poster bank',
  24, 36, 0.5, null,
  true,
  'checklist-refs/glb/posters/poster-vinyl-record.glb',
  'checklist-refs/images/posters/poster-vinyl-record.png',
  '{"vinyl","record","music","retro","black","classic","poster"}'::text[],
  ARRAY['decor_art'],
  'public'
),
(
  'poster-rain-moody',
  'Rainy moody city wall poster',
  'Rainy moody city wall poster — CC0/public-domain Toova poster bank',
  24, 36, 0.5, null,
  true,
  'checklist-refs/glb/posters/poster-rain-moody.glb',
  'checklist-refs/images/posters/poster-rain-moody.png',
  '{"rain","moody","city","grey","storm","urban","poster"}'::text[],
  ARRAY['decor_art'],
  'public'
),
(
  'poster-crystal-prism',
  'Crystal prism color wall poster',
  'Crystal prism color wall poster — CC0/public-domain Toova poster bank',
  24, 36, 0.5, null,
  true,
  'checklist-refs/glb/posters/poster-crystal-prism.glb',
  'checklist-refs/images/posters/poster-crystal-prism.png',
  '{"crystal","prism","color","rainbow","light","abstract","poster"}'::text[],
  ARRAY['decor_art'],
  'public'
),
(
  'poster-lightning-flash',
  'Lightning storm dramatic wall poster',
  'Lightning storm dramatic wall poster — CC0/public-domain Toova poster bank',
  24, 36, 0.5, null,
  true,
  'checklist-refs/glb/posters/poster-lightning-flash.glb',
  'checklist-refs/images/posters/poster-lightning-flash.png',
  '{"lightning","storm","dramatic","dark","flash","sky","poster"}'::text[],
  ARRAY['decor_art'],
  'public'
),
(
  'poster-balloon-sky',
  'Colorful balloon sky wall poster',
  'Colorful balloon sky wall poster — CC0/public-domain Toova poster bank',
  24, 36, 0.5, null,
  true,
  'checklist-refs/glb/posters/poster-balloon-sky.glb',
  'checklist-refs/images/posters/poster-balloon-sky.png',
  '{"balloon","sky","colorful","travel","adventure","cheerful","poster"}'::text[],
  ARRAY['decor_art'],
  'public'
),
(
  'poster-surf-tropical',
  'Tropical surf wave wall poster',
  'Tropical surf wave wall poster — CC0/public-domain Toova poster bank',
  24, 36, 0.5, null,
  true,
  'checklist-refs/glb/posters/poster-surf-tropical.glb',
  'checklist-refs/images/posters/poster-surf-tropical.png',
  '{"surf","tropical","wave","ocean","blue","beach","poster"}'::text[],
  ARRAY['decor_art'],
  'public'
),
(
  'poster-yoga-calm',
  'Calm yoga studio wall poster',
  'Calm yoga studio wall poster — CC0/public-domain Toova poster bank',
  24, 36, 0.5, null,
  true,
  'checklist-refs/glb/posters/poster-yoga-calm.glb',
  'checklist-refs/images/posters/poster-yoga-calm.png',
  '{"yoga","calm","green","wellness","soft","balance","poster"}'::text[],
  ARRAY['decor_art'],
  'public'
),
(
  'poster-film-noir',
  'Film noir monochrome wall poster',
  'Film noir monochrome wall poster — CC0/public-domain Toova poster bank',
  24, 36, 0.5, null,
  true,
  'checklist-refs/glb/posters/poster-film-noir.glb',
  'checklist-refs/images/posters/poster-film-noir.png',
  '{"film","noir","monochrome","black","white","classic","poster"}'::text[],
  ARRAY['decor_art'],
  'public'
),
(
  'poster-pop-dots',
  'Pop art dots wall poster',
  'Pop art dots wall poster — CC0/public-domain Toova poster bank',
  24, 36, 0.5, null,
  true,
  'checklist-refs/glb/posters/poster-pop-dots.glb',
  'checklist-refs/images/posters/poster-pop-dots.png',
  '{"pop","art","dots","colorful","bold","retro","poster"}'::text[],
  ARRAY['decor_art'],
  'public'
),
(
  'poster-sunset-band',
  'Sunset color band wall poster',
  'Sunset color band wall poster — CC0/public-domain Toova poster bank',
  24, 36, 0.5, null,
  true,
  'checklist-refs/glb/posters/poster-sunset-band.glb',
  'checklist-refs/images/posters/poster-sunset-band.png',
  '{"sunset","band","orange","pink","sky","warm","poster"}'::text[],
  ARRAY['decor_art'],
  'public'
),
(
  'poster-mint-fresh',
  'Mint green fresh wall poster',
  'Mint green fresh wall poster — CC0/public-domain Toova poster bank',
  24, 36, 0.5, null,
  true,
  'checklist-refs/glb/posters/poster-mint-fresh.glb',
  'checklist-refs/images/posters/poster-mint-fresh.png',
  '{"mint","green","fresh","soft","pastel","clean","poster"}'::text[],
  ARRAY['decor_art'],
  'public'
),
(
  'poster-rust-industrial',
  'Rust industrial texture wall poster',
  'Rust industrial texture wall poster — CC0/public-domain Toova poster bank',
  24, 36, 0.5, null,
  true,
  'checklist-refs/glb/posters/poster-rust-industrial.glb',
  'checklist-refs/images/posters/poster-rust-industrial.png',
  '{"rust","industrial","texture","warm","metal","urban","poster"}'::text[],
  ARRAY['decor_art'],
  'public'
),
(
  'poster-galaxy-spiral',
  'Galaxy spiral cosmos wall poster',
  'Galaxy spiral cosmos wall poster — CC0/public-domain Toova poster bank',
  24, 36, 0.5, null,
  true,
  'checklist-refs/glb/posters/poster-galaxy-spiral.glb',
  'checklist-refs/images/posters/poster-galaxy-spiral.png',
  '{"galaxy","spiral","cosmos","purple","space","stars","poster"}'::text[],
  ARRAY['decor_art'],
  'public'
),
(
  'poster-cloud-dreamy',
  'Dreamy cloud sky wall poster',
  'Dreamy cloud sky wall poster — CC0/public-domain Toova poster bank',
  24, 36, 0.5, null,
  true,
  'checklist-refs/glb/posters/poster-cloud-dreamy.glb',
  'checklist-refs/images/posters/poster-cloud-dreamy.png',
  '{"cloud","dreamy","sky","soft","blue","calm","poster"}'::text[],
  ARRAY['decor_art'],
  'public'
)
ON CONFLICT (kind) DO UPDATE
SET label = EXCLUDED.label,
    description = EXCLUDED.description,
    width_in = EXCLUDED.width_in,
    height_in = EXCLUDED.height_in,
    depth_in = EXCLUDED.depth_in,
    model_url = EXCLUDED.model_url,
    thumbnail_path = EXCLUDED.thumbnail_path,
    tags = EXCLUDED.tags,
    categories = EXCLUDED.categories,
    is_builtin = true,
    visibility = 'public';
